version: '3.2'

services:
  haproxy:
    image: my-haproxy
    restart: always
    ports:
        - "80:80"
        - "1936:1936"
    volumes:
      - type: bind
        source: ${PWD}/haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
    deploy:
      replicas: 4
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
